DROP DATABASE handytec-web;
CREATE DATABASE handytec-web CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'diego'@'localhost' IDENTIFIED BY 'dgl0588';
GRANT ALL PRIVILEGES ON *.* TO 'diego'@'localhost' WITH GRANT OPTION;
CREATE USER 'diego'@'%' IDENTIFIED BY 'dgl0588';
GRANT ALL PRIVILEGES ON *.* TO 'diego'@'%' WITH GRANT OPTION;

DROP TABLE CUSTOMER;
DROP TABLE PROJECT_PLAN;
DROP TABLE PARAMETER;

CREATE TABLE 'PARAMETER' (
  'CODE' varchar(6) NOT NULL,
  'PARAMETER' varchar(16) NOT NULL,
  'DESCRIPTION' varchar(256) NOT NULL,
  PRIMARY KEY ('CODE','PARAMETER')
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO PARAMETER values('CON', 'REQUIREMENT', 'CONSULTANCY SERVICES');
INSERT INTO PARAMETER values('DIA', 'REQUIREMENT', 'FREE DIAGNOSTIC');
INSERT INTO PARAMETER values('INF', 'REQUIREMENT', 'INFRAESTRUCTURE');
INSERT INTO PARAMETER values('ITS', 'REQUIREMENT', 'INFORMATION TECHNOLOGY SERVICES');
INSERT INTO PARAMETER values('MOB', 'ORIGIN', 'MOBILE DEVICE');
INSERT INTO PARAMETER values('MOB', 'REQUIREMENT', 'MOBILE APPLICATION');
INSERT INTO PARAMETER values('OTH', 'REQUIREMENT', 'OTHER');
INSERT INTO PARAMETER values('TRA', 'REQUIREMENT', 'TRAINING');
INSERT INTO PARAMETER values('WEB', 'ORIGIN', 'WEB BROWSER');
INSERT INTO PARAMETER values('WEB', 'REQUIREMENT', 'WEB SITE');
INSERT INTO PARAMETER values('WRK', 'REQUIREMENT', 'WORK WITH US');

CREATE TABLE 'CUSTOMER' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'DATE' datetime NOT NULL,
  'NAME' varchar(45) NOT NULL,
  'LAST_NAME' varchar(45) NOT NULL,
  'EMAIL' varchar(45) NOT NULL,
  'PHONE' varchar(15) NOT NULL,
  'COMPANY' varchar(45) DEFAULT NULL,
  'REQUIREMENT' varchar(6) NOT NULL,
  'ORIGIN' varchar(45) DEFAULT NULL,
  'SUSCRIBED' tinyint(4) NOT NULL DEFAULT '1',
  'SECTION' varchar(45) DEFAULT 'SERVICES',
  PRIMARY KEY ('ID'),
  KEY 'CODE_indx' ('REQUIREMENT'),
  KEY 'ORIGIN_indx' ('ORIGIN'),
  CONSTRAINT 'ORIGIN' FOREIGN KEY ('ORIGIN') REFERENCES 'PARAMETER' ('CODE') ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT 'REQUIREMENT' FOREIGN KEY ('REQUIREMENT') REFERENCES 'PARAMETER' ('CODE') ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE 'PROJECT_PLAN' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'DATE' datetime DEFAULT NULL,
  'NAME' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'LAST_NAME' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'COMPANY' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'ADDRESS' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'PHONE' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'EMAIL' varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  'SITE' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'IDEA' varchar(200) COLLATE latin1_spanish_ci NOT NULL,
  'SCOPE' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'BUDGET' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'DURATION' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'BDD' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'OPTIONAL_APP' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'PLATFORM' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  'ORIGIN' varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  PRIMARY KEY ('ID')
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;
